workflows:
    ios-workflow:
      name: ios_workflow
      instance_type: mac_mini_m1
      environment:
#         ios_signing:
#             distribution_type: app_store # or: ad_hoc | development | enterprise
#             bundle_identifier: com.mars.native-ios-app
        ios_signing:
          provisioning_profiles:
            - ios_profile
          certificates:
            - ios_cert
        groups:
           - ios
           - firebase_creds
           - firebase
           - slack
           - repo_credentials
        # # Add the group environment variables in Codemagic UI (either in Application/Team variables) - https://docs.codemagic.io/variables/environment-variable-groups/
        #   - app_store_credentials # <-- (APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY)
        #     # APP_STORE_CONNECT_ISSUER_ID <-- Put your App Store Connect Issuer Id here 
        #     # APP_STORE_CONNECT_KEY_IDENTIFIER <-- Put your App Store Connect Key Identifier here 
        #     # APP_STORE_CONNECT_PRIVATE_KEY <-- Put your App Store Connect Private Key here
        #     # See the following link for more details - https://docs.codemagic.io/code-signing-yaml/signing-ios/
        #     # https://appstoreconnect.apple.com/access/api
        #   - certificate_credentials # <-- (CERTIFICATE_PRIVATE_KEY - Put your Certificate Private Key here)
        #   - other
        vars:
          XCODE_WORKSPACE: "native_ios_app.xcworkspace" # <-- Put the name of your workspace here.
#           XCODE_SCHEME: "native_ios_app" # <-- Put the name of your scheme here.
#           BUNDLE_ID: "com.mars.native-ios-app" # <-- Put your Bundle Id here.
          XCODE_SCHEME: "native-ios" # <-- Put the name of your scheme here.
 
#           BUNDLE_ID: "com.mars.native-ios-app" # <-- Put your Bundle Id here.
          # APP_STORE_APP_ID: 1555555551 # <-- Put the app id number here. This is found in App Store Connect > App > General > App Information
        xcode: latest
        cocoapods: default
      cache:
           cache_paths:
               - $HOME/Library/Caches/CocoaPods
#       triggering:
#         events:
#           - push
#           - tag
#           - pull_request
#         branch_patterns:
#           - pattern: 'develop'
#             include: true
#             source: true
      scripts:
#         - name: 
#           script: |
#              rm -rf /Applications/Xcode.app
#          swift package init
#          xcodebuild -resolvePackageDependencies
#          echo $CM_BUILD_DIR
#         - name: Pod inst
#           script: |
#               pod install
#         - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
#           script: |
#             keychain initialize
#         - name: Fetch signing files
#           script: |
#             app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
#           app-store-connect fetch-signing-files com.mars.native-ios-appUITests.xctrunner --type IOS_APP_DEVELOPMENT --create
#         - name: Use system default keychain
#           script: |
#             keychain add-certificates
        - name: Git tags
          script: |
             git tag "test444"
             git push "https://icarusdust:${ACCESS_TOKEN}@github.com/icarusdust/native-ios-app.git" --tags 
 
        - name: Set up code signing settings on Xcode project
          script: |
            xcode-project use-profiles --custom-export-options='{"uploadBitcode": false, "uploadSymbols": false}'
#         - name: Increment build number
#           script: |
#             #!/bin/sh
#             set -e
#             set -x
#             cd $FCI_BUILD_DIR
#             # agvtool new-version -all $(($BUILD_NUMBER + 1))
#             agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1))
#         - name: Firebase 
#           script: |
#             xcodebuild -workspace native_ios_app.xcworkspace \
#             -scheme native-ios \
#             -derivedDataPath ./build/ios_integ \
#             -sdk iphoneos build-for-testing
#             cd ./build/ios_integ/Build/Products
#             zip -r "ios_tests.zip" "Debug-iphoneos" "native-ios_iphoneos15.4-arm64.xctestrun"
        - name: Build ipa for distribution
          script: |
            xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME" --archive-flags "-destination 'generic/platform=iOS'  CODE_SIGNING_REQUIRED=YES CODE_SIGNING_ALLOWED=NO"
#          xcodebuild build -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" CODE_SIGNING_REQUIRED=Yes CODE_SIGNING_ALLOWED=No
#         - name: Uploading to BrowserStack App Live environment
#           script: |
#             curl -p "nihalagazade_JxPH1i:4y5LkQnzzGkv2s7ERZ4q" -X POST "https://api-cloud.browserstack.com/app-live/upload" -F "file=@/Users/builder/clone/build/ios/ipa/native_ios_app.ipa"
#         - name: Test Lab upload
#           script: |
#                 echo $GCLOUD_KEY_FILE > ./gcloud_key_file.json
#                 gcloud auth activate-service-account --key-file=gcloud_key_file.json
#                 # Select YOUR Firebase project through which want to run the tests
#                 gcloud --quiet config set project $FIREBASE_PROJECT
#                 gcloud firebase test ios run --test "/Users/builder/clone/build/ios_integ/Build/Products/ios_tests.zip" \
#                 --device model=iphone11pro,version=14.7,locale=en_US,orientation=portrait \
#                 --xcode-version=13.3.1 \
#                 --timeout 10m
      artifacts:
        - build/ios/ipa/*.ipa
        - /tmp/xcodebuild_logs/*.log
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
        - /Users/builder/clone/build/ios_integ/Build/Products/ios_tests.zip
#       publishing:
#           email:
#             recipients:
#               - nihal@nevercode.io
#             notify:
#               success: true
#               failure: true
# #            scripts:
#              - name: Slack publishing
#                script: |
#                   theLink=$(echo $CM_ARTIFACT_LINKS | jq .[0].url)
#                   if [[ -z ${theLink} ]]
#                   then
#                     echo "No .ipa were found"
#                   else
#                      curl -d "text=Hi, please check your email. $theLink" -d "channel=slack_api" -H "Authorization: Bearer $SLACK_TOKEN" -X POST https://slack.com/api/chat.postMessage

#                   fi   
#                 channel: '#builds'
#                 notify_on_build_start: true    # To receive a notification when a build starts
#                 notify:
#                   success: false               # To not receive a notification when a build succeeds
#                   failure: false  
#         firebase:
#             firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
#             ios:
#               app_id: 1:796756497549:ios:98fbcde6b7d77a1ff13ec4 # Add your iOS app id retrieved from Firebase console
#               groups: # Add one or more groups that you wish to distribute your iOS application to, you can create groups in the Firebase console
#                 - iosTesters
